"""
Erebus Plugin - Redirector Config Generator

Generates C2 redirector configurations for Apache (mod_rewrite .htaccess),
Nginx (location block), and Caddy (Caddyfile) from operator-supplied C2
profile parameters.

Redirector architecture:
    Internet → redirector (Apache/Nginx/Caddy) → team server (never exposed)
    Any request NOT matching the C2 profile URI/UA pattern → decoy redirect

Why redirectors:
  - Team server IP never appears in victim DNS/connection logs
  - Decoy redirect (302 to legitimate site) confuses incident responders
  - UA/URI filtering lets sandbox traffic through as 302 (no payload returned)
  - Domain fronting: CDN Host header differs from SNI; allows team server hiding

OPSEC Notes:
  - Run redirectors on separate infra pool from team server
  - Use distinct domain pools per phase: OSINT / delivery / C2 never share IPs
  - Rotate redirector domain on burn indicator; never attempt to clean/reuse
  - TLS cert: Let's Encrypt auto-cert on redirector; self-signed = instant flag
  - Keep mod_rewrite / Nginx access logs OFF on redirectors to reduce OPSEC risk
    (or ship to SOC-isolated log store)

Reference: T1090.002 - External Proxy / Redirector
"""

import pathlib
import textwrap
from typing import Dict, Callable, Optional

try:
    from erebus_wrapper.erebus.modules.plugin_base import ErebusPlugin, PluginMetadata, PluginCategory
except ImportError:
    from plugin_base import ErebusPlugin, PluginMetadata, PluginCategory


# ---------------------------------------------------------------------------
# Apache mod_rewrite template
# ---------------------------------------------------------------------------
_APACHE_TEMPLATE = """\
# Erebus C2 Redirector - Apache mod_rewrite
# Generated by Erebus Wrapper
# ============================================================
# Install: copy to .htaccess in web root, or include in VirtualHost block.
# Requires: mod_rewrite, mod_proxy, mod_proxy_http (enabled via a2enmod).
# Proxy to team server: ProxyPass must be enabled (ProxyRequests Off).
# ============================================================

RewriteEngine On
Options -Indexes

# ── URI allowlist ────────────────────────────────────────────────────────────
# Only forward requests matching C2 profile URIs; 302 everything else.
{uri_rules}

# ── User-Agent allowlist ─────────────────────────────────────────────────────
# Forward if UA matches implant profile; drop sandbox/scanner UAs.
{ua_rules}

# ── Proxy: forward matched traffic to team server ────────────────────────────
RewriteRule ^(.*)$ {teamserver_url}%{{REQUEST_URI}} [P,L]
ProxyPassReverse / {teamserver_url}/

# ── Catch-all: redirect non-matching traffic to decoy ────────────────────────
# Incident responders hitting the redirector get a clean 302 to a real site.
RewriteRule ^(.*)$ {decoy_url} [R=302,L]
"""

_APACHE_URI_RULE = "RewriteCond %{{REQUEST_URI}} \"{uri}\" [NC]"
_APACHE_UA_RULE  = "RewriteCond %{{HTTP_USER_AGENT}} \"{ua}\" [NC]"


# ---------------------------------------------------------------------------
# Nginx template
# ---------------------------------------------------------------------------
_NGINX_TEMPLATE = """\
# Erebus C2 Redirector - Nginx
# Generated by Erebus Wrapper
# ============================================================
# Install: include in server {{ }} block (e.g. /etc/nginx/sites-enabled/c2.conf).
# Requires: nginx proxy module (usually built-in).
# HTTPS termination: pair with certbot (Let's Encrypt) for clean cert chain.
# ============================================================

server {{
    listen 443 ssl http2;
    server_name {server_name};

    # TLS - use certbot / Let's Encrypt; never self-signed on a redirector
    ssl_certificate     /etc/letsencrypt/live/{server_name}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/{server_name}/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # Disable access log to avoid victim connection records on redirector
    access_log off;
    error_log /var/log/nginx/c2_error.log warn;

    # ── C2 profile URI locations ─────────────────────────────────────────────
{location_blocks}

    # ── Catch-all: decoy redirect ─────────────────────────────────────────────
    location / {{
        return 302 {decoy_url};
    }}
}}
"""

_NGINX_LOCATION = """\
    location ~* {uri} {{
        # Forward only implant User-Agent
        if ($http_user_agent !~* "{ua_pattern}") {{
            return 302 {decoy_url};
        }}
        proxy_pass {teamserver_url};
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_ssl_verify off;
    }}"""


# ---------------------------------------------------------------------------
# Caddy template
# ---------------------------------------------------------------------------
_CADDY_TEMPLATE = """\
# Erebus C2 Redirector - Caddyfile
# Generated by Erebus Wrapper
# ============================================================
# Install: place in /etc/caddy/Caddyfile or include via import.
# Caddy auto-provisions Let's Encrypt TLS - no certbot needed.
# ============================================================

{server_name} {{
    # ── C2 profile URI routes ─────────────────────────────────────────────────
{route_blocks}

    # ── Catch-all: decoy redirect ─────────────────────────────────────────────
    respond * 302 {{
        header Location {decoy_url}
        close
    }}

    log {{
        output discard
    }}
}}
"""

_CADDY_ROUTE = """\
    @c2_{tag} {{
        path_regexp `{uri}`
        header User-Agent *{ua_keyword}*
    }}
    reverse_proxy @c2_{tag} {teamserver_url} {{
        transport http {{
            tls_insecure_skip_verify
        }}
    }}"""


# ---------------------------------------------------------------------------
# Terraform stub (DigitalOcean / AWS EC2 bootstrap)
# ---------------------------------------------------------------------------
_TERRAFORM_STUB = """\
# Erebus Redirector - Terraform bootstrap stub
# Generated by Erebus Wrapper
# ============================================================
# Provisions a DigitalOcean droplet + DNS A record for the redirector.
# Adjust provider, region, size, and ssh_keys for your environment.
# ============================================================

terraform {{
  required_providers {{
    digitalocean = {{
      source  = "digitalocean/digitalocean"
      version = "~> 2.0"
    }}
  }}
}}

variable "do_token" {{}}
variable "ssh_key_fingerprint" {{}}

provider "digitalocean" {{
  token = var.do_token
}}

resource "digitalocean_droplet" "redirector" {{
  name   = "erebus-redirector"
  region = "nyc3"       # [MALLEABLE] pick a region close to target geography
  size   = "s-1vcpu-1gb"
  image  = "ubuntu-22-04-x64"
  ssh_keys = [var.ssh_key_fingerprint]

  user_data = <<-EOF
    #!/bin/bash
    apt-get update -y
    apt-get install -y apache2 libapache2-mod-security2
    a2enmod rewrite proxy proxy_http ssl headers
    a2dissite 000-default
    systemctl restart apache2
    # TODO: drop .htaccess into /var/www/html/.htaccess and configure VirtualHost
  EOF

  tags = ["erebus", "redirector"]
}}

resource "digitalocean_record" "redirector" {{
  domain = "{server_name}"
  type   = "A"
  name   = "@"
  value  = digitalocean_droplet.redirector.ipv4_address
  ttl    = 60   # Short TTL during active ops for fast failover
}}

output "redirector_ip" {{
  value = digitalocean_droplet.redirector.ipv4_address
}}
"""


class InfraRedirectorPlugin(ErebusPlugin):
    """Generate Apache / Nginx / Caddy C2 redirector configs from profile params."""

    metadata = PluginMetadata(
        name="Infra Redirector",
        version="1.0.0",
        category=PluginCategory.TRIGGER,  # closest available; infra is a delivery enabler
        description="Generate C2 redirector configs (Apache/Nginx/Caddy) and Terraform bootstrap",
        author="Whispergate",
    )

    def get_metadata(self) -> PluginMetadata:
        return self.metadata

    def register(self) -> Dict[str, Callable]:
        return {
            "generate_redirector_configs": self.generate_redirector_configs,
        }

    def validate(self) -> tuple[bool, Optional[str]]:
        return True, None

    def on_load(self):
        pass

    # ------------------------------------------------------------------ #

    def generate_redirector_configs(
        self,
        output_dir: str,
        teamserver_url: str,
        server_name: str,
        c2_uris: Optional[list[str]] = None,
        ua_patterns: Optional[list[str]] = None,
        decoy_url: str = "https://www.microsoft.com/en-us/",
        include_apache: bool = True,
        include_nginx: bool = True,
        include_caddy: bool = True,
        include_terraform: bool = True,
    ) -> Dict[str, pathlib.Path]:
        """Generate C2 redirector configuration files for multiple web servers.

        Produces one config per requested platform plus an optional Terraform
        stub for rapid provisioning. All configs implement the same two-rule
        logic: forward C2-matching traffic to the team server, 302-redirect
        everything else to a decoy URL.

        Args:
            output_dir:      Directory to write generated config files into.
            teamserver_url:  Full URL of the hidden team server
                             (e.g. "https://10.0.0.5:8443"). Never exposed to
                             the public - only the redirector connects to it.
            server_name:     Public hostname for the redirector
                             (e.g. "cdn.legitimate-looking.com"). Used in Nginx
                             server_name directive and Caddy site address.
            c2_uris:         List of URI regex patterns to allowlist
                             (e.g. ["/api/v1/update", "/cdn/assets/.*\\.js"]).
                             Defaults to a generic profile if omitted.
            ua_patterns:     List of User-Agent substrings/regex to allowlist
                             (e.g. ["Mozilla/5.0.*Windows NT"]).
                             Defaults to a generic browser UA if omitted.
            decoy_url:       URL for catch-all 302 redirect. Pick a plausible
                             site matching the redirector's domain theme.
            include_apache:  Generate Apache .htaccess (default: True).
            include_nginx:   Generate Nginx config (default: True).
            include_caddy:   Generate Caddyfile (default: True).
            include_terraform: Generate Terraform DO stub (default: True).

        Returns:
            Dict mapping platform name → Path of generated config file.
            Keys: "apache", "nginx", "caddy", "terraform" (whichever enabled).
        """
        out = pathlib.Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)

        # Defaults - match a generic Mythic/Cobalt-style malleable profile
        if not c2_uris:
            c2_uris = [
                r"^/api/v[0-9]+/update",
                r"^/cdn/assets/.*\.js$",
                r"^/static/images/.*\.png$",
            ]
        if not ua_patterns:
            ua_patterns = [
                r"Mozilla/5\.0.*Windows NT.*rv:[0-9]",
                r"Mozilla/5\.0.*Macintosh.*AppleWebKit",
            ]

        teamserver_url = teamserver_url.rstrip("/")
        results: Dict[str, pathlib.Path] = {}

        # ── Apache ────────────────────────────────────────────────────────────
        if include_apache:
            uri_rules = "\n".join(
                _APACHE_URI_RULE.format(uri=u) for u in c2_uris
            )
            # All URI conditions must match (AND logic via chained RewriteCond)
            # Separate UA condition block follows
            ua_rules = "\n".join(
                _APACHE_UA_RULE.format(ua=ua) for ua in ua_patterns[:1]
            )
            apache_cfg = _APACHE_TEMPLATE.format(
                uri_rules=uri_rules,
                ua_rules=ua_rules,
                teamserver_url=teamserver_url,
                decoy_url=decoy_url,
            )
            p = out / ".htaccess"
            p.write_text(apache_cfg, encoding="utf-8")
            results["apache"] = p

        # ── Nginx ─────────────────────────────────────────────────────────────
        if include_nginx:
            # Build one location block per URI pattern
            ua_pattern = ua_patterns[0] if ua_patterns else "Mozilla"
            location_blocks = "\n\n".join(
                _NGINX_LOCATION.format(
                    uri=uri,
                    ua_pattern=ua_pattern,
                    teamserver_url=teamserver_url,
                    decoy_url=decoy_url,
                )
                for uri in c2_uris
            )
            nginx_cfg = _NGINX_TEMPLATE.format(
                server_name=server_name,
                location_blocks=location_blocks,
                teamserver_url=teamserver_url,
                decoy_url=decoy_url,
            )
            p = out / "nginx_c2.conf"
            p.write_text(nginx_cfg, encoding="utf-8")
            results["nginx"] = p

        # ── Caddy ─────────────────────────────────────────────────────────────
        if include_caddy:
            ua_keyword = ua_patterns[0].split(".*")[0] if ua_patterns else "Mozilla"
            # Strip regex metacharacters for Caddy glob match
            ua_keyword = ua_keyword.replace(r"\.", ".").replace("^", "").replace("$", "")
            route_blocks = "\n\n".join(
                _CADDY_ROUTE.format(
                    tag=f"route{i}",
                    uri=uri,
                    ua_keyword=ua_keyword,
                    teamserver_url=teamserver_url,
                )
                for i, uri in enumerate(c2_uris)
            )
            caddy_cfg = _CADDY_TEMPLATE.format(
                server_name=server_name,
                route_blocks=route_blocks,
                decoy_url=decoy_url,
            )
            p = out / "Caddyfile"
            p.write_text(caddy_cfg, encoding="utf-8")
            results["caddy"] = p

        # ── Terraform ─────────────────────────────────────────────────────────
        if include_terraform:
            tf_cfg = _TERRAFORM_STUB.format(server_name=server_name)
            p = out / "redirector.tf"
            p.write_text(tf_cfg, encoding="utf-8")
            results["terraform"] = p

        # ── README / operator notes ───────────────────────────────────────────
        readme_lines = [
            "# Erebus Redirector Configs",
            "",
            f"Team server  : {teamserver_url}",
            f"Public domain: {server_name}",
            f"Decoy URL    : {decoy_url}",
            "",
            "## C2 URI Allowlist",
            *[f"  {u}" for u in c2_uris],
            "",
            "## UA Allowlist",
            *[f"  {u}" for u in ua_patterns],
            "",
            "## Files",
            "  .htaccess      - Apache mod_rewrite (drop in web root)",
            "  nginx_c2.conf  - Nginx server block (symlink into sites-enabled/)",
            "  Caddyfile      - Caddy site block (import from global Caddyfile)",
            "  redirector.tf  - Terraform DigitalOcean bootstrap stub",
            "",
            "## Quick Deploy (Apache)",
            "  apt install apache2",
            "  a2enmod rewrite proxy proxy_http ssl headers",
            "  cp .htaccess /var/www/html/.htaccess",
            "  certbot --apache -d " + server_name,
            "",
            "## OPSEC",
            "  - Keep access logs OFF on redirector (log to isolated store if required)",
            "  - Destroy and reprovision redirector infra after each engagement",
            "  - Use separate IP/domain pools for OSINT, delivery, and C2 phases",
            "  - Short TTL (60s) during active ops for fast DNS failover",
        ]
        readme = out / "REDIRECTOR_README.md"
        readme.write_text("\n".join(readme_lines), encoding="utf-8")
        results["readme"] = readme

        return results


_plugin = InfraRedirectorPlugin()

if __name__ == "__main__":
    valid, err = _plugin.validate()
    print("[+] Validation passed" if valid else f"[-] Validation failed: {err}")
